# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ml_357QHptyj49LtmXVckKz11yzjGuTd
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile index.html
# <!DOCTYPE html>
# <html>
# <head>
#   <title>Exam Department Portal</title>
#   <style>
#     body {
#       font-family: Arial;
#       background-color: #f4f6f8;
#       margin: 20px;
#     }
#     h1 {
#       text-align: center;
#       color: #2c3e50;
#     }
#     h2 {
#       color: #34495e;
#       margin-top: 30px;
#     }
#     table {
#       width: 100%;
#       border-collapse: collapse;
#       background: white;
#     }
#     th, td {
#       border: 1px solid #ccc;
#       padding: 8px;
#       text-align: center;
#     }
#     th {
#       background-color: #3498db;
#       color: white;
#     }
#     .notice {
#       background: #fff3cd;
#       padding: 15px;
#       border-left: 5px solid #f1c40f;
#     }
#   </style>
# </head>
# 
# <body>
# 
# <h1>EXAM DEPARTMENT TEST RECORD</h1>
# 
# <h2>Student Year & Division</h2>
# <table>
#   <tr>
#     <th>Year</th>
#     <th>Division</th>
#   </tr>
#   <tr>
#     <td>SE</td>
#     <td>A / B</td>
#   </tr>
#   <tr>
#     <td>TE</td>
#     <td>A / B</td>
#   </tr>
#   <tr>
#     <td>BE</td>
#     <td>A / B</td>
#   </tr>
# </table>
# 
# <h2>Attendance Record</h2>
# <table>
#   <tr>
#     <th>Student Name</th>
#     <th>Year</th>
#     <th>Division</th>
#     <th>Attendance (%)</th>
#   </tr>
#   <tr>
#     <td>Student 1</td>
#     <td>SE</td>
#     <td>A</td>
#     <td>85%</td>
#   </tr>
# </table>
# 
# <h2>Marksheet</h2>
# <table>
#   <tr>
#     <th>Student Name</th>
#     <th>Subject</th>
#     <th>Marks</th>
#     <th>Status</th>
#   </tr>
#   <tr>
#     <td>Student 1</td>
#     <td>Maths</td>
#     <td>78</td>
#     <td>Pass</td>
#   </tr>
# </table>
# 
# <h2>Notice Board</h2>
# <div class="notice">
#   <ul>
#     <li>Mid-sem exam starts from 10 March</li>
#     <li>Attendance minimum required: 75%</li>
#     <li>Marksheet will be available after result declaration</li>
#   </ul>
# </div>
# 
# </body>
# </html>
#

from IPython.display import HTML
HTML(filename="index.html")